From danteev/texlive:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    python3.13-venv

RUN mkdir -p /TEX
WORKDIR /TEX
RUN git clone https://github.com/yukimaru77/texannotate.git
RUN curl -L https://install.perlbrew.pl | bash
RUN source ~/perl5/perlbrew/etc/bashrc && \
    perlbrew init
RUN perlbrew install --notest perl-5.22.4
RUN perlbrew switch perl-5.22.4
RUN perlbrew install-cpanm
RUN cpanm https://github.com/Fireblossom/TeX-AutoTeX-Mod.git

# 例: /TeX/texannotate/requirements.txt の htmlmin を htmlmin2 に置換してからインストール
RUN python3 -m venv venv && . venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r "$REQ"